### ISSUE TITLE
Per user locale causes breaking error

### ISSUE THREAD

**Issue by initsuj** [TheE/MyWarp#120] opened 2016-11-19 20:45 UTC
I recently installed MyWarp v3.0-beta-3+jenkins-b98.git-623f42c and it worked fine for several days. Users soon began having issues with any command (listing or going to warp locations), but there was no universal pattern to it. Some users were unaffected, but other couldn't use any of the commands. I finally found a console error showing that it was caused by an invalid locale format. I turned off per user formats and everything is now working.

[15:10:12] [Server thread/INFO]: voooodooo issued server command: /warp list
[15:10:12] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'warp' in plugin MyWarp v3.0-beta-3+jenkins-b98.git-623f42c
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-570526c-75a8885]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-570526c-75a8885]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358) [spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193) [spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-570526c-75a8885]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-570526c-75a8885]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: Invalid locale format: en_us
	at org.apache.commons.lang.LocaleUtils.toLocale(LocaleUtils.java:118) ~[spigot.jar:git-Spigot-570526c-75a8885]
	at me.taylorkelly.mywarp.bukkit.util.parametric.ReflectiveLocaleResolver.resolve(ReflectiveLocaleResolver.java:99) ~[?:?]
	at me.taylorkelly.mywarp.bukkit.BukkitPlayer.getLocale(BukkitPlayer.java:119) ~[?:?]
	at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onCommand(MyWarpPlugin.java:276) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-570526c-75a8885]
	... 15 more

**Comment by TheE** [comment] 2016-11-19 20:47
Yes, Mojang changed the formatting of the locales in 1.11 which brakes beta3. Please use the latest devBuild which fixes the issue.

Closing as duplicate of #116.

**Closed by TheE** 2016-11-19 20:47 UTC
