### ISSUE TITLE
Warps completely resetting randomly

### ISSUE THREAD

**Issue by blazex224** [TheE/MyWarp#113] opened 2016-08-05 20:27 UTC
I don't know what's causing this, but at random times after a server restart, warps completely reset and disappear. I'm using the version for 1.10
Thanks for any help!

**Comment by TheE** [comment] 2016-08-05 21:19
Are there any error messages visible in the console? Could you test with the latest [development build ](https://thee140.ci.cloudbees.com/job/mywarp3_bukkit/)?

Is there any pattern that involves the disappearing warps (e.g. they where created/updated shortly before the restart)? Can you check if these warps are written to the database?

**Comment by TheE** [comment] 2016-11-19 12:05
Closing as I cannot reproduce the issue without additional input.

**Closed by TheE** 2016-11-19 12:05 UTC
Labels: c: core, s: invalid, t: bug
