### ISSUE TITLE
Ownership change of a single warp affects all warps of a player

### ISSUE THREAD

**Issue by thegarfish** [TheE/MyWarp#53] opened 2015-06-30 19:53 UTC
After a player typed these things: I type these things

"in the order you see them
./warp set qe
./warp set QE
./warp set a
./warp set sjrc6
./warp remove we
qe*
./warp set qe
./warp set QE

and then I had all the warps"

Following this, the user had ownership of nearly every warp on the server. If you have any idea why this happened let me know.

HE ALSO CLAIMED - that /warp list may have been what caused the issue.

**Comment by thegarfish** [comment] 2015-06-30 19:59
Found out what happened.

/warp give <name> *

**Comment by TheE** [comment] 2015-06-30 20:45
Sorry, I do not quit understand what happened. A user of yours got ownership of a couple of existing warps that where not owned by him and claims that he only used the commands above?

What version of MyWarp are you using?

If you are using any of the 3.0 versions, are you sure that this user does not have any of the following permissions: `mywarp.override.use`, `mywarp.override.modify`, `mywarp.override.view`, `mywarp.override.*`? Does the user have access to the `warp give` command?

**Comment by thegarfish** [comment] 2015-07-01 11:08
I am using the latest dev build.

And yes, each user has access to mywarp.cmd.give

**Comment by TheE** [comment] 2015-07-01 18:45
What about the override permissions? Have you made sure that they do **not** have them?

**Comment by FearThe1337** [comment] 2015-09-05 17:30
Just had the same issue where a player was assigned ownership of every single warp on the server. The issue is found on these lines:
https://github.com/TheE/MyWarp/blob/master/mywarp-core/src/main/java/me/taylorkelly/mywarp/storage/RelationalWarpStorage.java#L389-L397

When updating the owner in the database, the owner is set as owner of all warps due to a missing WHERE warp_id = WARP_ID.
Due to this using the give command with a mysql database will result in that player owning all warps after a restart (since the database is only loaded on startup).

Would appreciate if this could be fixed.

**Comment by TheE** [comment] 2015-09-05 17:34
Yeiks. Will fix as soon as possible.

**Comment by TheE** [comment] 2015-09-05 23:01
Should be fixed in latest devBuild, an updated beta will be posted within the nest 24 hours.

**Closed** 2015-09-05 23:00 UTC
Labels: c: core, t: bug
