### ISSUE TITLE
Public/private warp limits resetting

### ISSUE THREAD

**Issue by ManMoobs** [TheE/MyWarp#112] opened 2016-08-04 20:34 UTC
Once you set the limit, it just resets to the default values.

**Comment by TheE** [comment] 2016-08-04 20:43
What version are you using?

**Comment by ManMoobs** [comment] 2016-08-04 20:47
b125 currently

**Comment by ManMoobs** [comment] 2016-08-04 20:48
Might i add, it doesnt really reset the values rather the plugin doesnt recognize the limits set and just uses default values.

**Comment by Terminologies** [comment] 2016-08-05 02:11
Yeah, I'm getting this same error with B125, all my plugins are current, my permissions plugin (zPermissions) is supported by vault, limits are configured, i have the permission nodes set in lexicographical order like the wiki said, the warp limits just stay at the defaultLimit configuration.

**Comment by TheE** [comment] 2016-08-05 09:36
I cannot reproduce this. For me, the default limit works as expected with build 125.

Could you send me your configuration file?

Also could you test if the problem is fixed by downgrading to [build 120](https://thee140.ci.cloudbees.com/job/mywarp3_bukkit/120/)? With build 121 I changed some things in the way the configuration is handled on Bukkit, maybe this this causes your problems.

**Comment by ManMoobs** [comment] 2016-08-05 13:18
you can change the limits for the default value, it's just that when you add custom limits and permissions, no matter what it uses the default limit.

**Comment by ManMoobs** [comment] 2016-08-05 13:24
Config:
http://pastebin.com/m1kYSZx0

**Comment by ManMoobs** [comment] 2016-08-05 13:38
Same problem with B120

**Comment by TheE** [comment] 2016-08-05 21:15
@ManMoobs This happens because you did not configure the custom bundles properly. They need to be indented below the `configuredTimers` and you need to remove the brackets like so:

```
  configuredLimits:
    b_vip:
      totalLimit: 5
      publicLimit: 5
      privateLimit: 5
    a_prime:
      totalLimit: 10
      publicLimit: 10
      privateLimit: 10
```
You can find a fixed version of your configuration file [here](http://pastebin.com/8iAGBb5m).

@Terminologies Could you please check if your problem is also caused by a mal formatted configuration file? Feel free to post it if you need help.

**Closed by TheE** 2016-08-05 21:15 UTC
Labels: t: bug

**Comment by Terminologies** [comment] 2016-08-06 03:42
Worked, 100% thank you very much. However, while it does show no brackets after configuredLimits in the wiki, maybe you should update the wiki to be more clear about it, because that was my mistake, I didn't know what it they were for and what I should do with them, therefore left them alone.
