### ISSUE TITLE
Private warps not being really private

### ISSUE THREAD

**Issue by 0x1x2** [TheE/MyWarp#128] opened 2017-01-18 03:25 UTC
Sorry for being late in replying to #127 - I updated to the latest devbuild and the issue is still present.

I'm creating private warps with /warp pcreate instead of /warp create + /warp private - is that the issue?

Server is on 1.10.2.

**Comment by 0x1x2** [comment] 2017-01-18 03:35
Plugins list: ScoreboardHotfix, SimpleBroadcast, Languages, MythicLib, PlugMan, CustomPolls, Spartan, DeluxeTags, DupePatch, TabListEdit, VKAutoPickup, ChatControl, FastAsyncWorldEdit, Vouchers, PermissionsEx, FeatherBoard, mcMMO, Lores, PlaceholderAPI, VoidWorld, VKBackPack, NametagEdit, Lockette, MyItems, OldCombatMechanics, TitleAPI, MultiSkyWars, VoxelSniper, LightAPI, WorldEdit, OpenInv, PacketListenerApi, BuycraftX, Votifier, VPNGuard, FastAsyncRedstone, MysteryBoxes, SQLibrary, CustomVillageTrades, Vault, PlayerPoints, ChestCommands, StaffPlus, MyWarp, MessageAnnouncer, Citizens, OnTime, ProtocolSupport, ObsidianAuctions, PerWorldInventory, WorldGuard, AuctionHouse, ASkyBlock, Essentials, SafeTrade, KitAdder, CS-CoreLib, EnjinMinecraftPlugin, RPGItems, NoFlyZone, ViaVersion, CommandNPC, QuickSell, BlockVersion, CompatNoCheatPlus, SilkSpawners, Multiverse-Core, ProtocolLib, Shopkeepers, ServerListPlus, MiniaturePets, ChestShop, EssentialsSpawn, HeadsPlugin, NoCheatPlus, LibsDisguises, eZProtector, HeavySpleef, Signs, CraftBook, Item2Chat, HolographicDisplays, PhatLoots, ServerSigns, ShopGUIPlus, pvparena, mcMMOAction, CrateReloaded, UltraCosmetics, HeadsInventory, ProtectionLib, PvPManager, MythicMobs, FurnitureLib, FurnitureMaker, MobStacker2, DiceFurniture, ProVotes, TokenEnchant, DeluxeChat, PrisonMines, EnchantmentBook, EBChance, Skript, SkStuff, skUtilities, skRayFall, SkQuery, Skellett, Umbaska, DailyBonus, LeaderHeads, ProQuests, ProQuests-Packages, BossShopPro, TrickyShops, ThirdCurrency

**Comment by TheE** [comment] 2017-01-18 21:23
Closing as duplicate of #127.

**Closed by TheE** 2017-01-18 21:23 UTC
Labels: c: bukkit-imp, c: core, s: duplicate, t: bug
