### ISSUE TITLE
Error On Some Computers

### ISSUE THREAD

**Issue by Mromashov** [TheE/MyWarp#110] opened 2016-07-24 19:26 UTC
When I try to make, use, or list my warps; I get an error message which says:
> An internal error occurred while attempting to perform this command

The message sent to console says:
> exception executing command 'warp' in plugin MyWarp v3.0-beta-3+jenkins-b98.git-623f42c
> java.lang.IllegalArgumentException: Invalid locale format: lol_US

This issue only occurs on my laptop. When I'm on my PC, it works perfectly.

**Comment by TheE** [comment] 2016-07-24 20:02
This was already fixed in 07f5f2e3401c3d3f2cd18e5f7683df001ce18d5d some time ago, please update to the latest devBuild.

The problem was caused by clients using the pirate language.

**Closed by TheE** 2016-07-24 20:02 UTC

**Comment by Mromashov** [comment] 2016-07-26 01:48
I wasn't using pirate language...

**Comment by TheE** [comment] 2016-07-29 09:41
One of your player's clients returned the locale `lol_US` which is the pirate language. This of course does not imply that you yourself used the pirate language.

Anyway it should all work fine if you use a current devBuild.
