### ISSUE TITLE
Multiple entries with same key

### ISSUE THREAD

**Issue by q220** [TheE/MyWarp#130] opened 2017-01-29 23:16 UTC
While trying to import from a pre3 legacy sql database, I encounter the following error:

````
[23:13:34 INFO]: Import started. This may take some time...
[23:13:34 INFO]: [MyWarp] 1960 entries found.
[23:13:34 INFO]: [MyWarp] Looking up unique IDs for 285 unique players.
[23:13:40 INFO]: Could not establish database connection in order to import warps: Multiple entries with same key: Ardelenia=afdb55e8-cb29-40ac-8860-f20ed30a624d and Ardelenia=afdb55e8-cb29-40ac-8860-f20ed30a624d
````

And it does not continue with the import.

**Comment by TheE** [comment] 2017-01-30 00:00
Seems like your old database was corrupted. Could you perhaps send it to me so I can take a look and (maybe) fix it?

**Comment by q220** [comment] 2017-01-30 01:30
Yeah sure, I still use this database on 2.6.5 every day and never encountered a problem with it. You can find it [here](http://build.mcmiddleearth.com/content/mywarp.sql)

**Comment by TheE** [comment] 2017-01-31 00:56
The database contains some duplicates (warps with a non unique name) which is why the import fails.

Even in MyWarp2 this should not have happened and I do not understand why MyWarp2 apparently still runs without problems given that the database contains duplicates, but the database code in MyWarp 2 was not exactly well written so... :/

To correctly import the database into MyWarp3 (which database code has been entirely rewritten and is much less likely to include any bugs!) you need to manually remove all duplicates so that **warp names are unique**. The import process cannot to this automatically because there is no way to know which of the duplicates should be retained.

Below you can find a list of the duplicated names:
````
  name: "annuminas"
  name: "Bar"
  name: "Black Gate"
  name: "Bree"
  name: "bunker"
  name: "cair andros"
  name: "castle"
  name: "CoL"
  name: "colcontest"
  name: "concept"
  name: "derp"
  name: "dome"
  name: "Edoras"
  name: "erebor"
  name: "ered luin"
  name: "eregion"
  name: "F1"
  name: "Fangorn"
  name: "fortress"
  name: "gladden"
  name: "GoblinTown"
  name: "Great Barrow"
  name: "head"
  name: "heads"
  name: "Henneth Annun"
  name: "Imloth"
  name: "ironhills"
  name: "ironmere"
  name: "Khazad-dûm"
  name: "L"
  name: "marda calderon"
  name: "Meduseld"
  name: "Moria"
  name: "MyHouse"
  name: "Plot 1"
  name: "rimaer"
  name: "show"
  name: "snow"
  name: "stash"
  name: "Tower"
  name: "Will"
  name: "xcair andros"
  name: "xmas"
  name: "xMoria East Gate"
  name: "zzz 333478 north"
  name: "zzz-eriol-glacierGate"
  name: "zzzDragonHorizonMinas"
````
Since you are using MySQL I assume you are familiar with databases and know how to remove the duplicates?

**Comment by q220** [comment] 2017-01-31 06:41
I think it might have something to do with MyWarp2 being case sensitive and seeing the warp 'bree' different as 'Bree' which might not be the case with MyWarp 3 (no more case sensitive?). I'm gonna see if I can remove the duplicates and will report back if it was solved or not :)

**Comment by q220** [comment] 2017-01-31 07:13
Okay so I'm still getting the same error even though the duplicate warp names are removed. Maybe it is related to the username? For some weird reason there are differences in capitalisation of the usernames at times.

**Comment by TheE** [comment] 2017-01-31 10:08
Could you please try again with the latest devBuild?

There was indeed an error related to user name parsing: Minecraft user names are case-insensitive but the conversion tried to return a UUID for all given cases. This should be fixed now.

Besides, just for your information: In MyWarp 3 warp names are still case-sensitive.

**Comment by q220** [comment] 2017-02-02 19:14
I tried out build 142 but the error is the same

> Could not establish database connection in order to import warps: Multiple entries with same key: Ardelenia=afdb55e8-cb29-40ac-8860-f20ed30a624d and Ardelenia=afdb55e8-cb29-40ac-8860-f20ed30a624d

**Comment by TheE** [comment] 2017-02-02 21:30
I cannot reproduce this. Running build 142 I managed to successfully import your warps from the dump you posted above.

Could you please check once more if you were really running build 142? It should say `[MyWarp] Enabling MyWarp v3.0-SNAPSHOT+jenkins-b142.git-2f620cce8a` on startup.

**Comment by q220** [comment] 2017-02-03 01:38
Ah yes wget quirked and made it a .1 file

I tested the command and it now tries to process; most warps are now taken over. But there are a fair few where it says 'no unique id could be found. The warp will be ignored', probably related due to someone who changed their name and the resolver not finding a match for that person?

**Comment by TheE** [comment] 2017-02-03 13:31
Yes, that is what I was seeing too.

Warps whose creators name cannot be converted into an UUID (e.g. because they changed their name).

**Closed by TheE** 2017-02-03 13:31 UTC
Labels: c: bukkit-imp, t: bug, t: question
