### ISSUE TITLE
Unknown symbol

### ISSUE THREAD

**Issue by Andreychik32** [TheE/MyWarp#61] opened 2015-09-19 13:28 UTC
Hi! My server is running Cauldron 1.7.10. I've installed MyWarp3.0-beta3 on my server. I've not changed any configs, only limits for players.
When player reach any limit, it will see this 
![minecraft 1 7 10](https://cloud.githubusercontent.com/assets/14360752/9976394/610c67ea-5eeb-11e5-98e4-deddcb3bea60.jpg)
How do I fix it?
Sorry for my bad english, I'm from Ukraine)

**Comment by TheE** [comment] 2015-09-20 00:00
I cannot reproduce this behaviour using CraftBukkit for 1.7.9. Is this the only message with such a symbol or are there more (from different plugins)?

This error does not really make sense since localization files where not altered. It is possible that Cauldron somehow mixed up the formatting, but I could not test it since there are no Cauldron downloads any more.

Speaking of localizations, if you are interested in contributing an Ukrainian localization to MyWarp, please let me know so I can setup the language at [crowdin](https://crowdin.com/project/mywarp).

**Comment by Andreychik32** [comment] 2015-09-20 08:45
I can see this symbol in commands /warp list and when I reach any created limit. Only in yours plugin.
I can contribute in Ukrainian localization, but it will take much time for me.

**Comment by Andreychik32** [comment] 2015-09-20 08:47
You can use this link to download Cauldron: http://sourceforge.net/projects/cauldron-unofficial/files/1.7.10/

**Comment by Andreychik32** [comment] 2015-09-23 20:45
And I can translate it to russian. Soon you'll fix this symbol

**Comment by TheE** [comment] 2016-03-07 10:36
Message handling has changed greatly within the last versions. Since I am unable to reproduce the problem, I am closing this issue.

However if the problem is not fixed, please reopen the issue!

**Closed by TheE** 2016-03-07 10:36 UTC
Labels: c: bukkit-imp, t: bug

**Comment by TheE** [comment] 2017-07-26 12:42
Hi, if you are still using MyWarp, this issue appears to be fixed now as I was finally able to understand why it happens (this bug only occurred when the server was running on Windows).

**Comment by Andreychik32** [comment] 2017-07-26 18:25
Thank you!
