### ISSUE TITLE
Won't load in 1.11

### ISSUE THREAD

**Issue by Ironic8b498** [TheE/MyWarp#119] opened 2016-11-19 14:53 UTC
I get the impression that this is only happening to me, I would like to know what I need to change to fix it so I can update my server. I have deleted the MyWarp folder and this still happens. 

`````
[09:46:12] [Server thread/ERROR]: [MyWarp] Failed to initialize warp storage.
me.taylorkelly.mywarp.warp.storage.StorageInitializationException: Failed to execute migration process.
	at me.taylorkelly.mywarp.warp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:105) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.MyWarp.initialize(MyWarp.java:115) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:118) [mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: me.taylorkelly.mywarp.internal.flyway.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
	at me.taylorkelly.mywarp.internal.flyway.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.execute(Flyway.java:1326) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.repair(Flyway.java:1106) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.warp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:102) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	... 13 more
Caused by: me.taylorkelly.mywarp.internal.h2.jdbc.JdbcSQLException: (Message 90020 not found) [90020-176]
	at me.taylorkelly.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.message.DbException.get(DbException.java:178) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.message.DbException.get(DbException.java:154) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.store.FileLock.getExceptionAlreadyInUse(FileLock.java:462) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.store.FileLock.lockFile(FileLock.java:356) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.store.FileLock.lock(FileLock.java:136) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.engine.Database.open(Database.java:622) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.engine.Database.openDatabase(Database.java:260) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.engine.Database.<init>(Database.java:254) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.engine.Engine.openSession(Engine.java:57) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.engine.Engine.openSession(Engine.java:164) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.engine.Engine.createSessionAndValidate(Engine.java:142) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.engine.Engine.createSession(Engine.java:125) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.engine.Engine.createSession(Engine.java:27) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.h2.Driver.connect(Driver.java:74) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_91]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0_91]
	at me.taylorkelly.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.initiate(SingleConnectionDataSource.java:170) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.getConnection(SingleConnectionDataSource.java:84) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.flyway.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.execute(Flyway.java:1326) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.repair(Flyway.java:1106) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	at me.taylorkelly.mywarp.warp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:102) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23130.jar:3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355]
	... 13 more
[09:46:12] [Server thread/ERROR]: [MyWarp] MyWarp is unable to continue and will be disabled.
[09:46:12] [Server thread/INFO]: [MyWarp] Disabling MyWarp v3.0-SNAPSHOT+jenkins-b130.git-4d9efb1355
`````

**Comment by TheE** [comment] 2016-11-19 14:58
Duplicate of #115. Let's keep it down to on ticket per issue.

**Closed by TheE** 2016-11-19 14:58 UTC
Labels: s: duplicate

**Comment by Ironic8b498** [comment] 2016-11-19 14:59
sorry forgot I opened the ticket already
