### ISSUE TITLE
Console SPAM error

### ISSUE THREAD

**Issue by NickFirenzo** [TheE/MyWarp#90] opened 2016-03-22 21:11 UTC
Getting console spam error, how can I fix it?
error: http://pastebin.com/69DrNeun

**Comment by TheE** [comment] 2016-03-23 21:25
there seems to be some sort of error with updating the name of the player who logged in. Could you please send me the full server log (there are several lines missing before and after the snippet posted above)?

**Comment by TheE** [comment] 2016-06-12 16:31
I am closing this issue as I am unable to reproduce it without additional information.

However, feel free to comment (and reopen) if you still encounter the issue!

**Closed by TheE** 2016-06-12 16:31 UTC
Labels: t: bug
