### ISSUE TITLE
IllegalArgumentException when inviting some players to warp 

### ISSUE THREAD

**Issue by Ghostlyr** [TheE/MyWarp#137] opened 2017-02-13 12:43 UTC
```
[MyWarp] The command 'warp invite cap_02 nikita_04_04' could not be executed.
me.taylorkelly.mywarp.internal.intake.InvocationCommandException: No input stream available
	at me.taylorkelly.mywarp.internal.intake.parametric.AbstractParametricCallable.call(AbstractParametricCallable.java:230) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.internal.intake.dispatcher.SimpleDispatcher.execute(SimpleDispatcher.java:192) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.internal.intake.dispatcher.SimpleDispatcher.call(SimpleDispatcher.java:175) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.internal.intake.dispatcher.SimpleDispatcher.execute(SimpleDispatcher.java:192) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.internal.intake.dispatcher.SimpleDispatcher.call(SimpleDispatcher.java:175) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.command.CommandHandler.callCommand(CommandHandler.java:204) [mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onCommand(MyWarpPlugin.java:208) [mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.55]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:417) [Essentials.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.55]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.55]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) [CraftServer.class:1.7.10-1614.55]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1366) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1103) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: No input stream available
	at me.taylorkelly.mywarp.internal.squirrelid.util.HttpRequest.returnContent(HttpRequest.java:224) ~[?:?]
	at me.taylorkelly.mywarp.internal.squirrelid.resolver.HttpRepositoryService.query(HttpRepositoryService.java:168) ~[?:?]
	at me.taylorkelly.mywarp.internal.squirrelid.resolver.HttpRepositoryService.findAllByName(HttpRepositoryService.java:141) ~[?:?]
	at me.taylorkelly.mywarp.internal.squirrelid.resolver.HttpRepositoryService.findByName(HttpRepositoryService.java:120) ~[?:?]
	at me.taylorkelly.mywarp.internal.squirrelid.resolver.CombinedProfileService.findByName(CombinedProfileService.java:76) ~[?:?]
	at me.taylorkelly.mywarp.internal.squirrelid.resolver.CacheForwardingService.findByName(CacheForwardingService.java:62) ~[?:?]
	at me.taylorkelly.mywarp.bukkit.SquirrelIdPlayerNameResolver.getByName(SquirrelIdPlayerNameResolver.java:104) ~[?:?]
	at me.taylorkelly.mywarp.command.SocialCommands.invite(SocialCommands.java:225) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at me.taylorkelly.mywarp.internal.intake.parametric.MethodCallable.call(MethodCallable.java:66) ~[?:?]
	at me.taylorkelly.mywarp.internal.intake.parametric.AbstractParametricCallable$1.call(AbstractParametricCallable.java:209) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
	at guava10.com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253) ~[MoreExecutors$SameThreadExecutorService.class:1.7.10-1614.55]
	at guava10.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:55) ~[AbstractListeningExecutorService.class:1.7.10-1614.55]
	at guava10.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:40) ~[AbstractListeningExecutorService.class:1.7.10-1614.55]
	at me.taylorkelly.mywarp.internal.intake.parametric.CommandExecutorWrapper.submit(CommandExecutorWrapper.java:44) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.internal.intake.parametric.AbstractParametricCallable.call(AbstractParametricCallable.java:206) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	... 23 more

```

Something similar was in #106
Last MyWarp dev build
1.7.10 [Thermos](https://github.com/TCPR/Thermos) b 55
Java 8u121

**Comment by TheE** [comment] 2017-02-13 21:55
The error occurs within the library that I am using to convert names to UUIDs on Bukkit, right when reading the contents of the response from Mojang's server.

Unfortunately I am unable to reproduce this issue; I tried to invite the player called `cap_02` which results in an error message (as it should):
![mywarp_issue137](https://cloud.githubusercontent.com/assets/1641994/22905019/e6bfea82-f23e-11e6-9569-bd02df918e5f.png)
This means that Mojang's server do not know a player named `cap_02` (see also [here](https://mcuuid.net/?q=cap_02)).

Could you please test if you are now seeing the same error as I did? Maybe Mojang's servers where offline or inaccessible for a short period of time.

**Comment by Ghostlyr** [comment] 2017-02-14 16:40
Yes, maybe the server was unavailable. Unable reproduce the problem again.

**Comment by TheE** [comment] 2017-02-14 22:21
I am closing this issue for now. Feel free to reopen it, if you are able to reproduce the error.

**Closed by TheE** 2017-02-14 22:21 UTC
Labels: c: bukkit-imp, t: bug
